### PR TITLE
Patch/update docker compose

### PR DESCRIPTION
**Pull request by jonathan-longe**
A couple of suggested changes for your consideration:

- update install.bash to use "docker compose" instead of "docker-compose".  My understanding is the "docker-compose" has been deprecated.  See:  https://stackoverflow.com/a/66516826
- create an uninstall.bash script to remove the docker images and volumes.  There's already an uninstall.bat we should have bash script too.
- finally modify .gitignore to exclude secrets and build artifacts from this repository.

### CODE REVIEW

**Comment by alanraju-aot** [comment]
> A couple of suggested changes for your consideration:
> 
> * update install.bash to use "docker compose" instead of "docker-compose".  My understanding is the "docker-compose" has been deprecated.  See:  https://stackoverflow.com/a/66516826
> * create an uninstall.bash script to remove the docker images and volumes.  There's already an uninstall.bat we should have bash script too.
> * finally modify .gitignore to exclude secrets and build artifacts from this repository.

That''s a great Jonathan.. We were planning to include these, let me test it once and will update

**Review by alanraju-aot — DISMISSED** [review]
These changes have already been added.. docker-compose to docker compose changes can be done later because we have lots of systems that do not support docker compose for bringing up the containers, so we can wait for that.

**Review by alanraju-aot — APPROVED** [review]

**Comment by uzrnem** [comment]
@kiran-aot @abilpraju-aot @formsflow-product-admin please look into this MR, changes looks good cc @alanraju-aot

**Review by abilpraju-aot — APPROVED** [review]
LGTM

**Comment by alanraju-aot** [comment]
Currently we are closing this as we have got these changes.

**Pull request closed without merging**
