### PR TITLE
Key name updated as per script file

### PR DESCRIPTION
**Pull request by uzrnem**
In scripts key used was `KEYCLOAK_ADMIN_USERNAME` and in docker file it was `KEYCLOAK_ADMIN_USER`

### CODE REVIEW

**Review by sreehari-aot — DISMISSED** [review]

**Comment by uzrnem** [comment]
@sreehari-aot can you help me get second approval. cc @alanraju-aot @auslin-aot

**Comment by sreehari-aot** [comment]
> @sreehari-aot can you help me get second approval. cc @alanraju-aot @auslin-aot

@uzrnem Really appreciate your contribution 👍 , our team will verify the changes.  @alanraju-aot pls have a check.

**Review by abilpraju-aot — APPROVED** [review]
LGTM

**Comment by uzrnem** [comment]
> > @sreehari-aot can you help me get second approval. cc @alanraju-aot @auslin-aot
> 
> @uzrnem Really appreciate your contribution +1 , our team will verify the changes. @alanraju-aot pls have a check.

@sreehari-aot Its my duty.

**Comment by uzrnem** [comment]
can anyone please merge this? I am not able to merge as I dont have write access cc @abilpraju-aot @alanraju-aot

**Comment by abhilash-aot** [comment]
Good Catch @uzrnem .  The env you have pointed out with the typo  "KEYCLOAK_ADMIN_USERNAME"  is not used anymore in webapi environment from v4.0.5. So basically the script need the modification rather than the env keys. We have already been working on that and minimized the env variable keys. Will be releasing the updated script by next week.

**Pull request closed without merging**
