### PR TITLE
Changes In the image tag to reflect next release version.

### PR DESCRIPTION
**Pull request by alanraju-aot**
# Issue Tracking

JIRA: 
Issue Type: https://aottech.atlassian.net/browse/FWF-3758

# Changes

* Update the image tag from v6.0.2 to v7.0.0-alpha
* updated the Realm for the latest keycloak version
* added the keycloak customisation and latest login theme

# Screenshots 

image

image

image

### CODE REVIEW

**Comment by sumesh-aot** [comment]
As mentioned in the previous PR please refer https://github.com/AOT-Technologies/forms-flow-ai/blob/develop/forms-flow-idm/keycloak/docker-compose.yml

**Review by sumesh-aot — CHANGES_REQUESTED** [review]
Purpose of keycloak-customizations is to not repeat the theme, realm changes.
please refer
https://github.com/AOT-Technologies/forms-flow-ai/blob/develop/forms-flow-idm/keycloak/Dockerfile
https://github.com/AOT-Technologies/forms-flow-ai/blob/develop/forms-flow-idm/keycloak/start-keycloak.sh

**Comment by alanraju-aot** [comment]
> Purpose of keycloak-customizations is to not repeat the theme, realm changes. please refer https://github.com/AOT-Technologies/forms-flow-ai/blob/develop/forms-flow-idm/keycloak/Dockerfile https://github.com/AOT-Technologies/forms-flow-ai/blob/develop/forms-flow-idm/keycloak/start-keycloak.sh

@sumesh-aot  I have tried with both scenarios. But without keycloak customization part and theme, the latest login theme was not visible.

**Comment by sumesh-aot** [comment]
> > Purpose of keycloak-customizations is to not repeat the theme, realm changes. please refer https://github.com/AOT-Technologies/forms-flow-ai/blob/develop/forms-flow-idm/keycloak/Dockerfile https://github.com/AOT-Technologies/forms-flow-ai/blob/develop/forms-flow-idm/keycloak/start-keycloak.sh
> 
> @sumesh-aot I have tried with both scenarios. But without keycloak customization part and theme, the latest login theme was not visible.

Then we need to fix the issue, cannot replicate files in multiple place

**Review by sumesh-aot — APPROVED** [review]

**Review by kiran-aot — APPROVED** [review]

**Pull request merged**
